version: "3.8"

services:
  app:
    container_name: task-api
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: npm run start
    restart: always

  mongo:
    image: mongo:6.0
    container_name: task-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: task-cache
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
